/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/editor/AppBar.vue')['default']
    EditorWrapper: typeof import('./src/components/editor/EditorWrapper.vue')['default']
    FooterBar: typeof import('./src/components/editor/FooterBar.vue')['default']
    LeftSideBar: typeof import('./src/components/editor/LeftSideBar.vue')['default']
    MainContent: typeof import('./src/components/editor/MainContent.vue')['default']
    RightSideBar: typeof import('./src/components/editor/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/editor/TimeLine.vue')['default']
    ToolBar: typeof import('./src/components/editor/ToolBar.vue')['default']
    UserMenu: typeof import('./src/components/common/UserMenu.vue')['default']
  }
}
